### PR TITLE
Add ULong to GenIncDec and remove duplicate UShort

### LINKED ISSUE #3: GenIncDec declares UShort twice and not ULong
https://github.com/jakobbotsch/Fuzzlyn/blob/master/Fuzzlyn/Methods/FuncGenerator.cs#L801

Should this be ULong?

### PR DESCRIPTION
**Pull request by rowandh**
Closes #3.

### CODE REVIEW

**Comment by jakobbotsch** [comment]
Thank you! Can you please bump the version to 1.1.2 too? This will change invalidate existing seeds.

**Comment by rowandh** [comment]
In Fuzzlyn.csproj? It's currently 1.1, do you mean bump it to 1.2 (not 1.1.2)?

**Comment by jakobbotsch** [comment]
Yes in Fuzzlyn.csproj is fine. I prefer 1.1.2 because this is a pretty minor change, when I bumped from 1.0 to 1.1 I added support for multiple features in the generator.

**Comment by rowandh** [comment]
Ok, was also confused by skipping 1.1.1 but I've updated the PR 😃

**Comment by jakobbotsch** [comment]
Thank you! Indeed 1.1.1 would have made more sense but not a big deal.

**Pull request merged**
